# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.define 'app0' do |app|
    app.vm.network "private_network", ip: "192.168.33.40"
    app.vm.hostname = "app0.vagrant"
  end
  config.vm.define 'app1' do |app|
    app.vm.network "private_network", ip: "192.168.33.41"
    app.vm.hostname = "app1.vagrant"
  end
  config.vm.define 'lb0' do |app|
    app.vm.network "private_network", ip: "192.168.33.42"
    app.vm.hostname = "lb0.vagrant"
  end
end
